from __future__ import annotations

from BaseClasses import Region
from typing import TYPE_CHECKING
if TYPE_CHECKING:    
    from .World import ManicMinersWorld

def create_and_connect_regions(world: ManicMinersWorld) -> None:
    create_all_regions(world)
    connect_regions(world)

def create_all_regions(world: ManicMinersWorld) -> None:
    region_menu = Region("Menu", world.player, world.multiworld)
    region_lrr_abreathoffreshair = Region("LRR - A Breath Of Fresh Air", world.player, world.multiworld)
    region_lrr_airraiders = Region("LRR - Air Raiders", world.player, world.multiworld)
    region_lrr_backtobasics = Region("LRR - Back To Basics", world.player, world.multiworld)
    region_lrr_breathless = Region("LRR - Breathless", world.player, world.multiworld)
    region_lrr_dontpanic = Region("LRR - Don't Panic", world.player, world.multiworld)
    region_lrr_drillernight = Region("LRR - Driller Night", world.player, world.multiworld)
    region_lrr_erodeworks = Region("LRR - Erode Works", world.player, world.multiworld)
    region_lrr_explosiveaction = Region("LRR - Explosive Action", world.player, world.multiworld)
    region_lrr_fireandwater = Region("LRR - Fire And Water", world.player, world.multiworld)
    region_lrr_frozenfrenzy = Region("LRR - Frozen Frenzy", world.player, world.multiworld)
    region_lrr_hotstuff = Region("LRR - Hot Stuff", world.player, world.multiworld)
    region_lrr_icespy = Region("LRR - Ice Spy", world.player, world.multiworld)
    region_lrr_itsaholdup = Region("LRR - It's A Hold Up", world.player, world.multiworld)
    region_lrr_lakeoffire = Region("LRR - Lake Of Fire", world.player, world.multiworld)
    region_lrr_lavalaughter = Region("LRR - Lava Laughter", world.player, world.multiworld)
    region_lrr_oresome = Region("LRR - Oresome", world.player, world.multiworld)
    region_lrr_rockhard = Region("LRR - Rock Hard", world.player, world.multiworld)
    region_lrr_rockyhorror = Region("LRR - Rocky Horror", world.player, world.multiworld)
    region_lrr_rubbletrouble = Region("LRR - Rubble Trouble", world.player, world.multiworld)
    region_lrr_runthegauntlet = Region("LRR - Run The Gauntlet", world.player, world.multiworld)
    region_lrr_searchandrescue = Region("LRR - Search And Rescue", world.player, world.multiworld)
    region_lrr_splitdownthemiddle = Region("LRR - Split Down The Middle", world.player, world.multiworld)
    region_lrr_thepathtopower = Region("LRR - The Path To Power", world.player, world.multiworld)
    region_lrr_waterlotoffun = Region("LRR - Water Lot Of Fun", world.player, world.multiworld)
    region_lrr_waterworks = Region("LRR - Water Works", world.player, world.multiworld)
    
    regions = [region_menu, region_lrr_abreathoffreshair, region_lrr_airraiders, region_lrr_backtobasics, region_lrr_breathless, region_lrr_dontpanic, region_lrr_drillernight, region_lrr_erodeworks, region_lrr_explosiveaction, region_lrr_fireandwater, region_lrr_frozenfrenzy, region_lrr_hotstuff, region_lrr_icespy, region_lrr_itsaholdup, region_lrr_lakeoffire, region_lrr_lavalaughter, region_lrr_oresome, region_lrr_rockhard, region_lrr_rockyhorror, region_lrr_rubbletrouble, region_lrr_runthegauntlet, region_lrr_searchandrescue, region_lrr_splitdownthemiddle, region_lrr_thepathtopower, region_lrr_waterlotoffun, region_lrr_waterworks]
    
    world.multiworld.regions += regions
    
def connect_regions(world: ManicMinersWorld) -> None:
    region_menu = world.get_region("Menu")
    region_lrr_abreathoffreshair = world.get_region("LRR - A Breath Of Fresh Air")
    region_lrr_airraiders = world.get_region("LRR - Air Raiders")
    region_lrr_backtobasics = world.get_region("LRR - Back To Basics")
    region_lrr_breathless = world.get_region("LRR - Breathless")
    region_lrr_dontpanic = world.get_region("LRR - Don't Panic")
    region_lrr_drillernight = world.get_region("LRR - Driller Night")
    region_lrr_erodeworks = world.get_region("LRR - Erode Works")
    region_lrr_explosiveaction = world.get_region("LRR - Explosive Action")
    region_lrr_fireandwater = world.get_region("LRR - Fire And Water")
    region_lrr_frozenfrenzy = world.get_region("LRR - Frozen Frenzy")
    region_lrr_hotstuff = world.get_region("LRR - Hot Stuff")
    region_lrr_icespy = world.get_region("LRR - Ice Spy")
    region_lrr_itsaholdup = world.get_region("LRR - It's A Hold Up")
    region_lrr_lakeoffire = world.get_region("LRR - Lake Of Fire")
    region_lrr_lavalaughter = world.get_region("LRR - Lava Laughter")
    region_lrr_oresome = world.get_region("LRR - Oresome")
    region_lrr_rockhard = world.get_region("LRR - Rock Hard")
    region_lrr_rockyhorror = world.get_region("LRR - Rocky Horror")
    region_lrr_rubbletrouble = world.get_region("LRR - Rubble Trouble")
    region_lrr_runthegauntlet = world.get_region("LRR - Run The Gauntlet")
    region_lrr_searchandrescue = world.get_region("LRR - Search And Rescue")
    region_lrr_splitdownthemiddle = world.get_region("LRR - Split Down The Middle")
    region_lrr_thepathtopower = world.get_region("LRR - The Path To Power")
    region_lrr_waterlotoffun = world.get_region("LRR - Water Lot Of Fun")
    region_lrr_waterworks = world.get_region("LRR - Water Works")
    
    region_menu.connect(region_lrr_abreathoffreshair, "Start Level - LRR - A Breath Of Fresh Air", lambda state: state.has("Level Access: LRR - A Breath Of Fresh Air", world.player))
    region_menu.connect(region_lrr_airraiders, "Start Level - LRR - Air Raiders", lambda state: state.has("Level Access: LRR - Air Raiders", world.player))
    region_menu.connect(region_lrr_backtobasics, "Start Level - LRR - Back To Basics", lambda state: state.has("Level Access: LRR - Back To Basics", world.player))
    region_menu.connect(region_lrr_breathless, "Start Level - LRR - Breathless", lambda state: state.has("Level Access: LRR - Breathless", world.player))
    region_menu.connect(region_lrr_dontpanic, "Start Level - LRR - Don't Panic", lambda state: state.has("Level Access: LRR - Don't Panic", world.player))
    region_menu.connect(region_lrr_drillernight, "Start Level - LRR - Driller Night", lambda state: state.has("Level Access: LRR - Driller Night", world.player))
    region_menu.connect(region_lrr_erodeworks, "Start Level - LRR - Erode Works", lambda state: state.has("Level Access: LRR - Erode Works", world.player))
    region_menu.connect(region_lrr_explosiveaction, "Start Level - LRR - Explosive Action", lambda state: state.has("Level Access: LRR - Explosive Action", world.player))
    region_menu.connect(region_lrr_fireandwater, "Start Level - LRR - Fire And Water", lambda state: state.has("Level Access: LRR - Fire And Water", world.player))
    region_menu.connect(region_lrr_frozenfrenzy, "Start Level - LRR - Frozen Frenzy", lambda state: state.has("Level Access: LRR - Frozen Frenzy", world.player))
    region_menu.connect(region_lrr_hotstuff, "Start Level - LRR - Hot Stuff", lambda state: state.has("Level Access: LRR - Hot Stuff", world.player))
    region_menu.connect(region_lrr_icespy, "Start Level - LRR - Ice Spy", lambda state: state.has("Level Access: LRR - Ice Spy", world.player))
    region_menu.connect(region_lrr_itsaholdup, "Start Level - LRR - It's A Hold Up", lambda state: state.has("Level Access: LRR - It's A Hold Up", world.player))
    region_menu.connect(region_lrr_lakeoffire, "Start Level - LRR - Lake Of Fire", lambda state: state.has("Level Access: LRR - Lake Of Fire", world.player))
    region_menu.connect(region_lrr_lavalaughter, "Start Level - LRR - Lava Laughter", lambda state: state.has("Level Access: LRR - Lava Laughter", world.player))
    region_menu.connect(region_lrr_oresome, "Start Level - LRR - Oresome", lambda state: state.has("Level Access: LRR - Oresome", world.player))
    region_menu.connect(region_lrr_rockhard, "Start Level - LRR - Rock Hard", lambda state: state.has("Level Access: LRR - Rock Hard", world.player))
    region_menu.connect(region_lrr_rockyhorror, "Start Level - LRR - Rocky Horror", lambda state: state.has("Level Access: LRR - Rocky Horror", world.player))
    region_menu.connect(region_lrr_rubbletrouble, "Start Level - LRR - Rubble Trouble", lambda state: state.has("Level Access: LRR - Rubble Trouble", world.player))
    region_menu.connect(region_lrr_runthegauntlet, "Start Level - LRR - Run The Gauntlet", lambda state: state.has("Level Access: LRR - Run The Gauntlet", world.player))
    region_menu.connect(region_lrr_searchandrescue, "Start Level - LRR - Search And Rescue", lambda state: state.has("Level Access: LRR - Search And Rescue", world.player))
    region_menu.connect(region_lrr_splitdownthemiddle, "Start Level - LRR - Split Down The Middle", lambda state: state.has("Level Access: LRR - Split Down The Middle", world.player))
    region_menu.connect(region_lrr_thepathtopower, "Start Level - LRR - The Path To Power", lambda state: state.has("Level Access: LRR - The Path To Power", world.player))
    region_menu.connect(region_lrr_waterlotoffun, "Start Level - LRR - Water Lot Of Fun", lambda state: state.has("Level Access: LRR - Water Lot Of Fun", world.player))
    region_menu.connect(region_lrr_waterworks, "Start Level - LRR - Water Works", lambda state: state.has("Level Access: LRR - Water Works", world.player))
    