from __future__ import annotations

from BaseClasses import Region
from typing import TYPE_CHECKING
if TYPE_CHECKING:    
    from .World import ManicMinersWorld

def create_and_connect_regions(world: ManicMinersWorld) -> None:
    create_all_regions(world)
    connect_regions(world)

def create_all_regions(world: ManicMinersWorld) -> None:
    region_menu = Region("Menu", world.player, world.multiworld)
    
    region_lrr_abreathoffreshair = Region("LRR - A Breath Of Fresh Air", world.player, world.multiworld)
    region_lrr_airraiders = Region("LRR - Air Raiders", world.player, world.multiworld)
    region_lrr_backtobasics = Region("LRR - Back To Basics", world.player, world.multiworld)
    region_lrr_breathless = Region("LRR - Breathless", world.player, world.multiworld)
    region_lrr_dontpanic = Region("LRR - Don't Panic", world.player, world.multiworld)
    region_lrr_drillernight = Region("LRR - Driller Night", world.player, world.multiworld)
    region_lrr_erodeworks = Region("LRR - Erode Works", world.player, world.multiworld)
    region_lrr_explosiveaction = Region("LRR - Explosive Action", world.player, world.multiworld)
    region_lrr_fireandwater = Region("LRR - Fire And Water", world.player, world.multiworld)
    region_lrr_frozenfrenzy = Region("LRR - Frozen Frenzy", world.player, world.multiworld)
    region_lrr_hotstuff = Region("LRR - Hot Stuff", world.player, world.multiworld)
    region_lrr_icespy = Region("LRR - Ice Spy", world.player, world.multiworld)
    region_lrr_itsaholdup = Region("LRR - It's A Hold Up", world.player, world.multiworld)
    region_lrr_lakeoffire = Region("LRR - Lake Of Fire", world.player, world.multiworld)
    region_lrr_lavalaughter = Region("LRR - Lava Laughter", world.player, world.multiworld)
    region_lrr_oresome = Region("LRR - Oresome", world.player, world.multiworld)
    region_lrr_rockhard = Region("LRR - Rock Hard", world.player, world.multiworld)
    region_lrr_rockyhorror = Region("LRR - Rocky Horror", world.player, world.multiworld)
    region_lrr_rubbletrouble = Region("LRR - Rubble Trouble", world.player, world.multiworld)
    region_lrr_runthegauntlet = Region("LRR - Run The Gauntlet", world.player, world.multiworld)
    region_lrr_searchandrescue = Region("LRR - Search And Rescue", world.player, world.multiworld)
    region_lrr_splitdownthemiddle = Region("LRR - Split Down The Middle", world.player, world.multiworld)
    region_lrr_thepathtopower = Region("LRR - The Path To Power", world.player, world.multiworld)
    region_lrr_waterlotoffun = Region("LRR - Water Lot Of Fun", world.player, world.multiworld)
    region_lrr_waterworks = Region("LRR - Water Works", world.player, world.multiworld)
    
    region_lrrr_abreathoffreshair = Region("LRRR - A Breath Of Fresh Air", world.player, world.multiworld)
    region_lrrr_airraiders = Region("LRRR - Air Raiders", world.player, world.multiworld)
    region_lrrr_backtobasics = Region("LRRR - Back To Basics", world.player, world.multiworld)
    region_lrrr_breathless = Region("LRRR - Breathless", world.player, world.multiworld)
    region_lrrr_dontpanic = Region("LRRR - Don't Panic", world.player, world.multiworld)
    region_lrrr_drillernight = Region("LRRR - Driller Night", world.player, world.multiworld)
    region_lrrr_erodeworks = Region("LRRR - Erode Works", world.player, world.multiworld)
    region_lrrr_explosiveaction = Region("LRRR - Explosive Action", world.player, world.multiworld)
    region_lrrr_fireandwater = Region("LRRR - Fire And Water", world.player, world.multiworld)
    region_lrrr_frozenfrenzy = Region("LRRR - Frozen Frenzy", world.player, world.multiworld)
    region_lrrr_hotstuff = Region("LRRR - Hot Stuff", world.player, world.multiworld)
    region_lrrr_icespy = Region("LRRR - Ice Spy", world.player, world.multiworld)
    region_lrrr_itsaholdup = Region("LRRR - It's A Hold Up", world.player, world.multiworld)
    region_lrrr_lakeoffire = Region("LRRR - Lake Of Fire", world.player, world.multiworld)
    region_lrrr_lavalaughter = Region("LRRR - Lava Laughter", world.player, world.multiworld)
    region_lrrr_oresome = Region("LRRR - Oresome", world.player, world.multiworld)
    region_lrrr_rockhard = Region("LRRR - Rock Hard", world.player, world.multiworld)
    region_lrrr_rockyhorror = Region("LRRR - Rocky Horror", world.player, world.multiworld)
    region_lrrr_rubbletrouble = Region("LRRR - Rubble Trouble", world.player, world.multiworld)
    region_lrrr_runthegauntlet = Region("LRRR - Run The Gauntlet", world.player, world.multiworld)
    region_lrrr_searchandrescue = Region("LRRR - Search And Rescue", world.player, world.multiworld)
    region_lrrr_splitdownthemiddle = Region("LRRR - Split Down The Middle", world.player, world.multiworld)
    region_lrrr_thepathtopower = Region("LRRR - The Path To Power", world.player, world.multiworld)
    region_lrrr_waterlotoffun = Region("LRRR - Water Lot Of Fun", world.player, world.multiworld)
    region_lrrr_waterworks = Region("LRRR - Water Works", world.player, world.multiworld)
    
    region_lrrc_abreathoffreshair = Region("LRRC - A Breath Of Fresh Air", world.player, world.multiworld)
    region_lrrc_airraiders = Region("LRRC - Air Raiders", world.player, world.multiworld)
    region_lrrc_backtobasics = Region("LRRC - Back To Basics", world.player, world.multiworld)
    region_lrrc_breathless = Region("LRRC - Breathless", world.player, world.multiworld)
    region_lrrc_dontpanic = Region("LRRC - Don't Panic", world.player, world.multiworld)
    region_lrrc_drillernight = Region("LRRC - Driller Night", world.player, world.multiworld)
    region_lrrc_erodeworks = Region("LRRC - Erode Works", world.player, world.multiworld)
    region_lrrc_explosiveaction = Region("LRRC - Explosive Action", world.player, world.multiworld)
    region_lrrc_fireandwater = Region("LRRC - Fire And Water", world.player, world.multiworld)
    region_lrrc_frozenfrenzy = Region("LRRC - Frozen Frenzy", world.player, world.multiworld)
    region_lrrc_hotstuff = Region("LRRC - Hot Stuff", world.player, world.multiworld)
    region_lrrc_icespy = Region("LRRC - Ice Spy", world.player, world.multiworld)
    region_lrrc_itsaholdup = Region("LRRC - It's A Hold Up", world.player, world.multiworld)
    region_lrrc_lakeoffire = Region("LRRC - Lake Of Fire", world.player, world.multiworld)
    region_lrrc_lavalaughter = Region("LRRC - Lava Laughter", world.player, world.multiworld)
    region_lrrc_oresome = Region("LRRC - Oresome", world.player, world.multiworld)
    region_lrrc_rockhard = Region("LRRC - Rock Hard", world.player, world.multiworld)
    region_lrrc_rockyhorror = Region("LRRC - Rocky Horror", world.player, world.multiworld)
    region_lrrc_rubbletrouble = Region("LRRC - Rubble Trouble", world.player, world.multiworld)
    region_lrrc_runthegauntlet = Region("LRRC - Run The Gauntlet", world.player, world.multiworld)
    region_lrrc_searchandrescue = Region("LRRC - Search And Rescue", world.player, world.multiworld)
    region_lrrc_splitdownthemiddle = Region("LRRC - Split Down The Middle", world.player, world.multiworld)
    region_lrrc_thepathtopower = Region("LRRC - The Path To Power", world.player, world.multiworld)
    region_lrrc_waterlotoffun = Region("LRRC - Water Lot Of Fun", world.player, world.multiworld)
    region_lrrc_waterworks = Region("LRRC - Water Works", world.player, world.multiworld)
    
    region_baz_abreathoffreshair = Region("BAZ - A Breath Of Fresh Air", world.player, world.multiworld)
    region_baz_airraiders = Region("BAZ - Air Raiders", world.player, world.multiworld)
    region_baz_backtobasics = Region("BAZ - Back To Basics", world.player, world.multiworld)
    region_baz_breathless = Region("BAZ - Breathless", world.player, world.multiworld)
    region_baz_coldcomfort = Region("BAZ - Cold Comfort", world.player, world.multiworld)
    region_baz_dontpanic = Region("BAZ - Don't Panic", world.player, world.multiworld)
    region_baz_downinthedirt = Region("BAZ - Down In The Dirt", world.player, world.multiworld)
    region_baz_drillernight = Region("BAZ - Driller Night", world.player, world.multiworld)
    region_baz_erodeworks = Region("BAZ - Erode Works", world.player, world.multiworld)
    region_baz_explosiveaction = Region("BAZ - Explosive Action", world.player, world.multiworld)
    region_baz_fireandwater = Region("BAZ - Fire And Water", world.player, world.multiworld)
    region_baz_frozenfrenzy = Region("BAZ - Frozen Frenzy", world.player, world.multiworld)
    region_baz_hotstuff = Region("BAZ - Hot Stuff", world.player, world.multiworld)
    region_baz_icespy = Region("BAZ - Ice Spy", world.player, world.multiworld)
    region_baz_itsaholdup = Region("BAZ - It's A Hold Up", world.player, world.multiworld)
    region_baz_lakeoffire = Region("BAZ - Lake Of Fire", world.player, world.multiworld)
    region_baz_lavalaughter = Region("BAZ - Lava Laughter", world.player, world.multiworld)
    region_baz_mineovermatter = Region("BAZ - Mine Over Matter", world.player, world.multiworld)
    region_baz_moltenmeltdown = Region("BAZ - Molten Meltdown", world.player, world.multiworld)
    region_baz_oresome = Region("BAZ - Oresome", world.player, world.multiworld)
    region_baz_recruitment = Region("BAZ - Recruitment", world.player, world.multiworld)
    region_baz_rockhard = Region("BAZ - Rock Hard", world.player, world.multiworld)
    region_baz_rockyhorror = Region("BAZ - Rocky Horror", world.player, world.multiworld)
    region_baz_rubbletrouble = Region("BAZ - Rubble Trouble", world.player, world.multiworld)
    region_baz_runthegauntlet = Region("BAZ - Run The Gauntlet", world.player, world.multiworld)
    region_baz_seamless = Region("BAZ - Seamless", world.player, world.multiworld)
    region_baz_searchandrescue = Region("BAZ - Search And Rescue", world.player, world.multiworld)
    region_baz_slimeysimple = Region("BAZ - Slimey Simple", world.player, world.multiworld)
    region_baz_splitdownthemiddle = Region("BAZ - Split Down The Middle", world.player, world.multiworld)
    region_baz_thehardrocklife = Region("BAZ - The Hard Rock Life", world.player, world.multiworld)
    region_baz_thepathtopower = Region("BAZ - The Path To Power", world.player, world.multiworld)
    region_baz_waterlotoffun = Region("BAZ - Water Lot Of Fun", world.player, world.multiworld)
    region_baz_waterworks = Region("BAZ - Water Works", world.player, world.multiworld)
    
    regions_lrr = [region_lrr_abreathoffreshair, region_lrr_airraiders, region_lrr_backtobasics, region_lrr_breathless, region_lrr_dontpanic, region_lrr_drillernight, region_lrr_erodeworks, region_lrr_explosiveaction, region_lrr_fireandwater, region_lrr_frozenfrenzy, region_lrr_hotstuff, region_lrr_icespy, region_lrr_itsaholdup, region_lrr_lakeoffire, region_lrr_lavalaughter, region_lrr_oresome, region_lrr_rockhard, region_lrr_rockyhorror, region_lrr_rubbletrouble, region_lrr_runthegauntlet, region_lrr_searchandrescue, region_lrr_splitdownthemiddle, region_lrr_thepathtopower, region_lrr_waterlotoffun, region_lrr_waterworks]
    regions_lrrr = [region_lrrr_abreathoffreshair, region_lrrr_airraiders, region_lrrr_backtobasics, region_lrrr_breathless, region_lrrr_dontpanic, region_lrrr_drillernight, region_lrrr_erodeworks, region_lrrr_explosiveaction, region_lrrr_fireandwater, region_lrrr_frozenfrenzy, region_lrrr_hotstuff, region_lrrr_icespy, region_lrrr_itsaholdup, region_lrrr_lakeoffire, region_lrrr_lavalaughter, region_lrrr_oresome, region_lrrr_rockhard, region_lrrr_rockyhorror, region_lrrr_rubbletrouble, region_lrrr_runthegauntlet, region_lrrr_searchandrescue, region_lrrr_splitdownthemiddle, region_lrrr_thepathtopower, region_lrrr_waterlotoffun, region_lrrr_waterworks]
    regions_lrrc = [region_lrrc_abreathoffreshair, region_lrrc_airraiders, region_lrrc_backtobasics, region_lrrc_breathless, region_lrrc_dontpanic, region_lrrc_drillernight, region_lrrc_erodeworks, region_lrrc_explosiveaction, region_lrrc_fireandwater, region_lrrc_frozenfrenzy, region_lrrc_hotstuff, region_lrrc_icespy, region_lrrc_itsaholdup, region_lrrc_lakeoffire, region_lrrc_lavalaughter, region_lrrc_oresome, region_lrrc_rockhard, region_lrrc_rockyhorror, region_lrrc_rubbletrouble, region_lrrc_runthegauntlet, region_lrrc_searchandrescue, region_lrrc_splitdownthemiddle, region_lrrc_thepathtopower, region_lrrc_waterlotoffun, region_lrrc_waterworks]
    regions_baz = [region_baz_abreathoffreshair, region_baz_airraiders, region_baz_backtobasics, region_baz_breathless, region_baz_coldcomfort, region_baz_dontpanic, region_baz_downinthedirt, region_baz_drillernight, region_baz_erodeworks, region_baz_explosiveaction, region_baz_fireandwater, region_baz_frozenfrenzy, region_baz_hotstuff, region_baz_icespy, region_baz_itsaholdup, region_baz_lakeoffire, region_baz_lavalaughter, region_baz_mineovermatter, region_baz_moltenmeltdown, region_baz_oresome, region_baz_recruitment, region_baz_rockhard, region_baz_rockyhorror, region_baz_rubbletrouble, region_baz_runthegauntlet, region_baz_seamless, region_baz_searchandrescue, region_baz_slimeysimple, region_baz_splitdownthemiddle, region_baz_thehardrocklife, region_baz_thepathtopower, region_baz_waterlotoffun, region_baz_waterworks]
    
    regions = [region_menu] + regions_lrr + regions_lrrr + regions_lrrc + regions_baz
    
    world.multiworld.regions += regions
    
def connect_regions(world: ManicMinersWorld) -> None:
    region_menu = world.get_region("Menu")
    
    region_lrr_abreathoffreshair = world.get_region("LRR - A Breath Of Fresh Air")
    region_lrr_airraiders = world.get_region("LRR - Air Raiders")
    region_lrr_backtobasics = world.get_region("LRR - Back To Basics")
    region_lrr_breathless = world.get_region("LRR - Breathless")
    region_lrr_dontpanic = world.get_region("LRR - Don't Panic")
    region_lrr_drillernight = world.get_region("LRR - Driller Night")
    region_lrr_erodeworks = world.get_region("LRR - Erode Works")
    region_lrr_explosiveaction = world.get_region("LRR - Explosive Action")
    region_lrr_fireandwater = world.get_region("LRR - Fire And Water")
    region_lrr_frozenfrenzy = world.get_region("LRR - Frozen Frenzy")
    region_lrr_hotstuff = world.get_region("LRR - Hot Stuff")
    region_lrr_icespy = world.get_region("LRR - Ice Spy")
    region_lrr_itsaholdup = world.get_region("LRR - It's A Hold Up")
    region_lrr_lakeoffire = world.get_region("LRR - Lake Of Fire")
    region_lrr_lavalaughter = world.get_region("LRR - Lava Laughter")
    region_lrr_oresome = world.get_region("LRR - Oresome")
    region_lrr_rockhard = world.get_region("LRR - Rock Hard")
    region_lrr_rockyhorror = world.get_region("LRR - Rocky Horror")
    region_lrr_rubbletrouble = world.get_region("LRR - Rubble Trouble")
    region_lrr_runthegauntlet = world.get_region("LRR - Run The Gauntlet")
    region_lrr_searchandrescue = world.get_region("LRR - Search And Rescue")
    region_lrr_splitdownthemiddle = world.get_region("LRR - Split Down The Middle")
    region_lrr_thepathtopower = world.get_region("LRR - The Path To Power")
    region_lrr_waterlotoffun = world.get_region("LRR - Water Lot Of Fun")
    region_lrr_waterworks = world.get_region("LRR - Water Works")
    
    region_lrrr_abreathoffreshair = world.get_region("LRRR - A Breath Of Fresh Air")
    region_lrrr_airraiders = world.get_region("LRRR - Air Raiders")
    region_lrrr_backtobasics = world.get_region("LRRR - Back To Basics")
    region_lrrr_breathless = world.get_region("LRRR - Breathless")
    region_lrrr_dontpanic = world.get_region("LRRR - Don't Panic")
    region_lrrr_drillernight = world.get_region("LRRR - Driller Night")
    region_lrrr_erodeworks = world.get_region("LRRR - Erode Works")
    region_lrrr_explosiveaction = world.get_region("LRRR - Explosive Action")
    region_lrrr_fireandwater = world.get_region("LRRR - Fire And Water")
    region_lrrr_frozenfrenzy = world.get_region("LRRR - Frozen Frenzy")
    region_lrrr_hotstuff = world.get_region("LRRR - Hot Stuff")
    region_lrrr_icespy = world.get_region("LRRR - Ice Spy")
    region_lrrr_itsaholdup = world.get_region("LRRR - It's A Hold Up")
    region_lrrr_lakeoffire = world.get_region("LRRR - Lake Of Fire")
    region_lrrr_lavalaughter = world.get_region("LRRR - Lava Laughter")
    region_lrrr_oresome = world.get_region("LRRR - Oresome")
    region_lrrr_rockhard = world.get_region("LRRR - Rock Hard")
    region_lrrr_rockyhorror = world.get_region("LRRR - Rocky Horror")
    region_lrrr_rubbletrouble = world.get_region("LRRR - Rubble Trouble")
    region_lrrr_runthegauntlet = world.get_region("LRRR - Run The Gauntlet")
    region_lrrr_searchandrescue = world.get_region("LRRR - Search And Rescue")
    region_lrrr_splitdownthemiddle = world.get_region("LRRR - Split Down The Middle")
    region_lrrr_thepathtopower = world.get_region("LRRR - The Path To Power")
    region_lrrr_waterlotoffun = world.get_region("LRRR - Water Lot Of Fun")
    region_lrrr_waterworks = world.get_region("LRRR - Water Works")
    
    region_lrrc_abreathoffreshair = world.get_region("LRRC - A Breath Of Fresh Air")
    region_lrrc_airraiders = world.get_region("LRRC - Air Raiders")
    region_lrrc_backtobasics = world.get_region("LRRC - Back To Basics")
    region_lrrc_breathless = world.get_region("LRRC - Breathless")
    region_lrrc_dontpanic = world.get_region("LRRC - Don't Panic")
    region_lrrc_drillernight = world.get_region("LRRC - Driller Night")
    region_lrrc_erodeworks = world.get_region("LRRC - Erode Works")
    region_lrrc_explosiveaction = world.get_region("LRRC - Explosive Action")
    region_lrrc_fireandwater = world.get_region("LRRC - Fire And Water")
    region_lrrc_frozenfrenzy = world.get_region("LRRC - Frozen Frenzy")
    region_lrrc_hotstuff = world.get_region("LRRC - Hot Stuff")
    region_lrrc_icespy = world.get_region("LRRC - Ice Spy")
    region_lrrc_itsaholdup = world.get_region("LRRC - It's A Hold Up")
    region_lrrc_lakeoffire = world.get_region("LRRC - Lake Of Fire")
    region_lrrc_lavalaughter = world.get_region("LRRC - Lava Laughter")
    region_lrrc_oresome = world.get_region("LRRC - Oresome")
    region_lrrc_rockhard = world.get_region("LRRC - Rock Hard")
    region_lrrc_rockyhorror = world.get_region("LRRC - Rocky Horror")
    region_lrrc_rubbletrouble = world.get_region("LRRC - Rubble Trouble")
    region_lrrc_runthegauntlet = world.get_region("LRRC - Run The Gauntlet")
    region_lrrc_searchandrescue = world.get_region("LRRC - Search And Rescue")
    region_lrrc_splitdownthemiddle = world.get_region("LRRC - Split Down The Middle")
    region_lrrc_thepathtopower = world.get_region("LRRC - The Path To Power")
    region_lrrc_waterlotoffun = world.get_region("LRRC - Water Lot Of Fun")
    region_lrrc_waterworks = world.get_region("LRRC - Water Works")
    
    region_baz_abreathoffreshair = world.get_region("BAZ - A Breath Of Fresh Air")
    region_baz_airraiders = world.get_region("BAZ - Air Raiders")
    region_baz_backtobasics = world.get_region("BAZ - Back To Basics")
    region_baz_breathless = world.get_region("BAZ - Breathless")
    region_baz_coldcomfort = world.get_region("BAZ - Cold Comfort")
    region_baz_dontpanic = world.get_region("BAZ - Don't Panic")
    region_baz_downinthedirt = world.get_region("BAZ - Down In The Dirt")
    region_baz_drillernight = world.get_region("BAZ - Driller Night")
    region_baz_erodeworks = world.get_region("BAZ - Erode Works")
    region_baz_explosiveaction = world.get_region("BAZ - Explosive Action")
    region_baz_fireandwater = world.get_region("BAZ - Fire And Water")
    region_baz_frozenfrenzy = world.get_region("BAZ - Frozen Frenzy")
    region_baz_hotstuff = world.get_region("BAZ - Hot Stuff")
    region_baz_icespy = world.get_region("BAZ - Ice Spy")
    region_baz_itsaholdup = world.get_region("BAZ - It's A Hold Up")
    region_baz_lakeoffire = world.get_region("BAZ - Lake Of Fire")
    region_baz_lavalaughter = world.get_region("BAZ - Lava Laughter")
    region_baz_mineovermatter = world.get_region("BAZ - Mine Over Matter")
    region_baz_moltenmeltdown = world.get_region("BAZ - Molten Meltdown")
    region_baz_oresome = world.get_region("BAZ - Oresome")
    region_baz_recruitment = world.get_region("BAZ - Recruitment")
    region_baz_rockhard = world.get_region("BAZ - Rock Hard")
    region_baz_rockyhorror = world.get_region("BAZ - Rocky Horror")
    region_baz_rubbletrouble = world.get_region("BAZ - Rubble Trouble")
    region_baz_runthegauntlet = world.get_region("BAZ - Run The Gauntlet")
    region_baz_seamless = world.get_region("BAZ - Seamless")
    region_baz_searchandrescue = world.get_region("BAZ - Search And Rescue")
    region_baz_slimeysimple = world.get_region("BAZ - Slimey Simple")
    region_baz_splitdownthemiddle = world.get_region("BAZ - Split Down The Middle")
    region_baz_thehardrocklife = world.get_region("BAZ - The Hard Rock Life")
    region_baz_thepathtopower = world.get_region("BAZ - The Path To Power")
    region_baz_waterlotoffun = world.get_region("BAZ - Water Lot Of Fun")
    region_baz_waterworks = world.get_region("BAZ - Water Works")
    
    region_menu.connect(region_lrr_abreathoffreshair, "Start Level - LRR - A Breath Of Fresh Air")
    region_menu.connect(region_lrr_airraiders, "Start Level - LRR - Air Raiders")
    region_menu.connect(region_lrr_backtobasics, "Start Level - LRR - Back To Basics")
    region_menu.connect(region_lrr_breathless, "Start Level - LRR - Breathless")
    region_menu.connect(region_lrr_dontpanic, "Start Level - LRR - Don't Panic")
    region_menu.connect(region_lrr_drillernight, "Start Level - LRR - Driller Night")
    region_menu.connect(region_lrr_erodeworks, "Start Level - LRR - Erode Works")
    region_menu.connect(region_lrr_explosiveaction, "Start Level - LRR - Explosive Action")
    region_menu.connect(region_lrr_fireandwater, "Start Level - LRR - Fire And Water")
    region_menu.connect(region_lrr_frozenfrenzy, "Start Level - LRR - Frozen Frenzy")
    region_menu.connect(region_lrr_hotstuff, "Start Level - LRR - Hot Stuff")
    region_menu.connect(region_lrr_icespy, "Start Level - LRR - Ice Spy")
    region_menu.connect(region_lrr_itsaholdup, "Start Level - LRR - It's A Hold Up")
    region_menu.connect(region_lrr_lakeoffire, "Start Level - LRR - Lake Of Fire")
    region_menu.connect(region_lrr_lavalaughter, "Start Level - LRR - Lava Laughter")
    region_menu.connect(region_lrr_oresome, "Start Level - LRR - Oresome")
    region_menu.connect(region_lrr_rockhard, "Start Level - LRR - Rock Hard")
    region_menu.connect(region_lrr_rockyhorror, "Start Level - LRR - Rocky Horror")
    region_menu.connect(region_lrr_rubbletrouble, "Start Level - LRR - Rubble Trouble")
    region_menu.connect(region_lrr_runthegauntlet, "Start Level - LRR - Run The Gauntlet")
    region_menu.connect(region_lrr_searchandrescue, "Start Level - LRR - Search And Rescue")
    region_menu.connect(region_lrr_splitdownthemiddle, "Start Level - LRR - Split Down The Middle")
    region_menu.connect(region_lrr_thepathtopower, "Start Level - LRR - The Path To Power")
    region_menu.connect(region_lrr_waterlotoffun, "Start Level - LRR - Water Lot Of Fun")
    region_menu.connect(region_lrr_waterworks, "Start Level - LRR - Water Works")
    
    region_menu.connect(region_lrrr_abreathoffreshair, "Start Level - LRRR - A Breath Of Fresh Air")
    region_menu.connect(region_lrrr_airraiders, "Start Level - LRRR - Air Raiders")
    region_menu.connect(region_lrrr_backtobasics, "Start Level - LRRR - Back To Basics")
    region_menu.connect(region_lrrr_breathless, "Start Level - LRRR - Breathless")
    region_menu.connect(region_lrrr_dontpanic, "Start Level - LRRR - Don't Panic")
    region_menu.connect(region_lrrr_drillernight, "Start Level - LRRR - Driller Night")
    region_menu.connect(region_lrrr_erodeworks, "Start Level - LRRR - Erode Works")
    region_menu.connect(region_lrrr_explosiveaction, "Start Level - LRRR - Explosive Action")
    region_menu.connect(region_lrrr_fireandwater, "Start Level - LRRR - Fire And Water")
    region_menu.connect(region_lrrr_frozenfrenzy, "Start Level - LRRR - Frozen Frenzy")
    region_menu.connect(region_lrrr_hotstuff, "Start Level - LRRR - Hot Stuff")
    region_menu.connect(region_lrrr_icespy, "Start Level - LRRR - Ice Spy")
    region_menu.connect(region_lrrr_itsaholdup, "Start Level - LRRR - It's A Hold Up")
    region_menu.connect(region_lrrr_lakeoffire, "Start Level - LRRR - Lake Of Fire")
    region_menu.connect(region_lrrr_lavalaughter, "Start Level - LRRR - Lava Laughter")
    region_menu.connect(region_lrrr_oresome, "Start Level - LRRR - Oresome")
    region_menu.connect(region_lrrr_rockhard, "Start Level - LRRR - Rock Hard")
    region_menu.connect(region_lrrr_rockyhorror, "Start Level - LRRR - Rocky Horror")
    region_menu.connect(region_lrrr_rubbletrouble, "Start Level - LRRR - Rubble Trouble")
    region_menu.connect(region_lrrr_runthegauntlet, "Start Level - LRRR - Run The Gauntlet")
    region_menu.connect(region_lrrr_searchandrescue, "Start Level - LRRR - Search And Rescue")
    region_menu.connect(region_lrrr_splitdownthemiddle, "Start Level - LRRR - Split Down The Middle")
    region_menu.connect(region_lrrr_thepathtopower, "Start Level - LRRR - The Path To Power")
    region_menu.connect(region_lrrr_waterlotoffun, "Start Level - LRRR - Water Lot Of Fun")
    region_menu.connect(region_lrrr_waterworks, "Start Level - LRRR - Water Works")

    region_menu.connect(region_lrrc_abreathoffreshair, "Start Level - LRRC - A Breath Of Fresh Air")
    region_menu.connect(region_lrrc_airraiders, "Start Level - LRRC - Air Raiders")
    region_menu.connect(region_lrrc_backtobasics, "Start Level - LRRC - Back To Basics")
    region_menu.connect(region_lrrc_breathless, "Start Level - LRRC - Breathless")
    region_menu.connect(region_lrrc_dontpanic, "Start Level - LRRC - Don't Panic")
    region_menu.connect(region_lrrc_drillernight, "Start Level - LRRC - Driller Night")
    region_menu.connect(region_lrrc_erodeworks, "Start Level - LRRC - Erode Works")
    region_menu.connect(region_lrrc_explosiveaction, "Start Level - LRRC - Explosive Action")
    region_menu.connect(region_lrrc_fireandwater, "Start Level - LRRC - Fire And Water")
    region_menu.connect(region_lrrc_frozenfrenzy, "Start Level - LRRC - Frozen Frenzy")
    region_menu.connect(region_lrrc_hotstuff, "Start Level - LRRC - Hot Stuff")
    region_menu.connect(region_lrrc_icespy, "Start Level - LRRC - Ice Spy")
    region_menu.connect(region_lrrc_itsaholdup, "Start Level - LRRC - It's A Hold Up")
    region_menu.connect(region_lrrc_lakeoffire, "Start Level - LRRC - Lake Of Fire")
    region_menu.connect(region_lrrc_lavalaughter, "Start Level - LRRC - Lava Laughter")
    region_menu.connect(region_lrrc_oresome, "Start Level - LRRC - Oresome")
    region_menu.connect(region_lrrc_rockhard, "Start Level - LRRC - Rock Hard")
    region_menu.connect(region_lrrc_rockyhorror, "Start Level - LRRC - Rocky Horror")
    region_menu.connect(region_lrrc_rubbletrouble, "Start Level - LRRC - Rubble Trouble")
    region_menu.connect(region_lrrc_runthegauntlet, "Start Level - LRRC - Run The Gauntlet")
    region_menu.connect(region_lrrc_searchandrescue, "Start Level - LRRC - Search And Rescue")
    region_menu.connect(region_lrrc_splitdownthemiddle, "Start Level - LRRC - Split Down The Middle")
    region_menu.connect(region_lrrc_thepathtopower, "Start Level - LRRC - The Path To Power")
    region_menu.connect(region_lrrc_waterlotoffun, "Start Level - LRRC - Water Lot Of Fun")
    region_menu.connect(region_lrrc_waterworks, "Start Level - LRRC - Water Works")

    region_menu.connect(region_baz_abreathoffreshair, "Start Level - BAZ - A Breath Of Fresh Air")
    region_menu.connect(region_baz_airraiders, "Start Level - BAZ - Air Raiders")
    region_menu.connect(region_baz_backtobasics, "Start Level - BAZ - Back To Basics")
    region_menu.connect(region_baz_breathless, "Start Level - BAZ - Breathless")
    region_menu.connect(region_baz_coldcomfort, "Start Level - BAZ - Cold Comfort")
    region_menu.connect(region_baz_dontpanic, "Start Level - BAZ - Don't Panic")
    region_menu.connect(region_baz_downinthedirt, "Start Level - BAZ - Down In The Dirt")
    region_menu.connect(region_baz_drillernight, "Start Level - BAZ - Driller Night")
    region_menu.connect(region_baz_erodeworks, "Start Level - BAZ - Erode Works")
    region_menu.connect(region_baz_explosiveaction, "Start Level - BAZ - Explosive Action")
    region_menu.connect(region_baz_fireandwater, "Start Level - BAZ - Fire And Water")
    region_menu.connect(region_baz_frozenfrenzy, "Start Level - BAZ - Frozen Frenzy")
    region_menu.connect(region_baz_hotstuff, "Start Level - BAZ - Hot Stuff")
    region_menu.connect(region_baz_icespy, "Start Level - BAZ - Ice Spy")
    region_menu.connect(region_baz_itsaholdup, "Start Level - BAZ - It's A Hold Up")
    region_menu.connect(region_baz_lakeoffire, "Start Level - BAZ - Lake Of Fire")
    region_menu.connect(region_baz_lavalaughter, "Start Level - BAZ - Lava Laughter")
    region_menu.connect(region_baz_mineovermatter, "Start Level - BAZ - Mine Over Matter")
    region_menu.connect(region_baz_moltenmeltdown, "Start Level - BAZ - Molten Meltdown")
    region_menu.connect(region_baz_oresome, "Start Level - BAZ - Oresome")
    region_menu.connect(region_baz_recruitment, "Start Level - BAZ - Recruitment")
    region_menu.connect(region_baz_rockhard, "Start Level - BAZ - Rock Hard")
    region_menu.connect(region_baz_rockyhorror, "Start Level - BAZ - Rocky Horror")
    region_menu.connect(region_baz_rubbletrouble, "Start Level - BAZ - Rubble Trouble")
    region_menu.connect(region_baz_runthegauntlet, "Start Level - BAZ - Run The Gauntlet")
    region_menu.connect(region_baz_seamless, "Start Level - BAZ - Seamless")
    region_menu.connect(region_baz_searchandrescue, "Start Level - BAZ - Search And Rescue")
    region_menu.connect(region_baz_slimeysimple, "Start Level - BAZ - Slimey Simple")
    region_menu.connect(region_baz_splitdownthemiddle, "Start Level - BAZ - Split Down The Middle")
    region_menu.connect(region_baz_thehardrocklife, "Start Level - BAZ - The Hard Rock Life")
    region_menu.connect(region_baz_thepathtopower, "Start Level - BAZ - The Path To Power")
    region_menu.connect(region_baz_waterlotoffun, "Start Level - BAZ - Water Lot Of Fun")
    region_menu.connect(region_baz_waterworks, "Start Level - BAZ - Water Works")

