from __future__ import annotations

from worlds.generic.Rules import set_rule, add_rule
from rule_builder.rules import Has, HasAll, HasAny, OptionFilter, Filtered
from . import Items
from . import Options as ManicMiners_Options

from typing import TYPE_CHECKING
if TYPE_CHECKING:    
    from .World import ManicMinersWorld

def set_all_rules(world: ManicMinersWorld) -> None:
    set_all_entrance_rules(world)
    set_all_location_rules(world)
    set_completion_condition(world)
    
def set_all_entrance_rules(world: ManicMinersWorld) -> None:
    
    rule_can_build_toolstore = Has("Building Unlock: Tool Store")
    rule_can_build_teleportpad = HasAll("Building Unlock: Teleport Pad", "Building Unlock: Power Station")
    rule_can_build_powerstation = rule_can_build_teleportpad
    rule_can_build_docks = Has("Building Unlock: Docks") & rule_can_build_powerstation
    rule_can_build_canteen = Has("Building Unlock: Canteen")
    rule_can_build_supportstation = Has("Building Unlock: Support Station") & rule_can_build_powerstation
    rule_can_build_geologicalcenter = Has("Building Unlock: Geological Center") & rule_can_build_powerstation
    rule_can_build_upgradestation = Has("Building Unlock: Upgrade Station") & rule_can_build_powerstation
    rule_can_build_orerefinery = Has("Building Unlock: Ore Refinery") & rule_can_build_powerstation
    rule_can_build_mininglaser = Has("Building Unlock: Mining Laser") & rule_can_build_supportstation
    rule_can_build_superteleport = Has("Building Unlock: Super Teleport") & rule_can_build_supportstation
    rule_can_breathe = rule_can_build_supportstation
    rule_can_always_breathe = Filtered(rule_can_breathe, options = [OptionFilter(ManicMiners_Options.BreathingAlwaysInLogic, 1)], filtered_resolution = True)
    rule_can_build_smalldigger = Has("Vehicle Unlock: Small Digger") & rule_can_build_supportstation & Filtered(rule_can_build_upgradestation, options = [OptionFilter(ManicMiners_Options.FasterBlastingAlwaysInLogic, 1)], filtered_resolution = True)
    rule_can_build_smlc = Has("Vehicle Unlock: Small Mobile Laser Cutter") & rule_can_build_supportstation & Filtered(rule_can_build_upgradestation, options = [OptionFilter(ManicMiners_Options.FasterBlastingAlwaysInLogic, 1)], filtered_resolution = True)
    rule_can_build_rapidrider = rule_can_build_docks & Has("Vehicle Unlock: Rapid Rider")
    rule_can_build_cargocarrier = rule_can_build_docks & Has("Vehicle Unlock: Cargo Carrier")
    rule_can_build_tunnelscout = rule_can_build_teleportpad & Has("Vehicle Unlock: Tunnel Scout")
    rule_can_build_tunneltransport = rule_can_build_superteleport & Has("Vehicle Unlock: Tunnel Transport")
    rule_can_build_hoverscout = rule_can_build_teleportpad & Has("Vehicle Unlock: Tunnel Scout")
    rule_can_build_granitegrinder = rule_can_build_superteleport & Has("Vehicle Unlock: Granite Grinder")
    rule_can_jump = rule_can_build_hoverscout | rule_can_build_granitegrinder
    rule_can_fly = rule_can_build_tunnelscout | rule_can_build_tunneltransport
    rule_can_swim = rule_can_fly | rule_can_build_rapidrider | rule_can_build_cargocarrier
    rule_can_vehicle_lase = rule_can_build_smlc | (HasAny("Vehicle Unlock: Chrome Crusher","Vehicle Unlock: Large Mobile Laser Cutter") & rule_can_build_superteleport)
    rule_can_lase = rule_can_vehicle_lase | rule_can_build_mininglaser
    rule_can_flying_lase = rule_can_vehicle_lase & rule_can_build_tunneltransport
    rule_can_flydrill = (rule_can_build_tunnelscout & rule_can_build_upgradestation) | rule_can_flying_lase
    rule_can_blast = Has("Item Unlock: Dynamite") | rule_can_lase | rule_can_build_smalldigger | rule_can_build_granitegrinder

    #LRR

    entrance_lrr_abreathoffreshair = world.get_entrance("Start Level - LRR - A Breath Of Fresh Air")
    entrance_lrr_airraiders = world.get_entrance("Start Level - LRR - Air Raiders")
    entrance_lrr_backtobasics = world.get_entrance("Start Level - LRR - Back To Basics")
    entrance_lrr_breathless = world.get_entrance("Start Level - LRR - Breathless")
    entrance_lrr_dontpanic = world.get_entrance("Start Level - LRR - Don't Panic")
    entrance_lrr_drillernight = world.get_entrance("Start Level - LRR - Driller Night")
    entrance_lrr_erodeworks = world.get_entrance("Start Level - LRR - Erode Works")
    entrance_lrr_explosiveaction = world.get_entrance("Start Level - LRR - Explosive Action")
    entrance_lrr_fireandwater = world.get_entrance("Start Level - LRR - Fire And Water")
    entrance_lrr_frozenfrenzy = world.get_entrance("Start Level - LRR - Frozen Frenzy")
    entrance_lrr_hotstuff = world.get_entrance("Start Level - LRR - Hot Stuff")
    entrance_lrr_icespy = world.get_entrance("Start Level - LRR - Ice Spy")
    entrance_lrr_itsaholdup = world.get_entrance("Start Level - LRR - It's A Hold Up")
    entrance_lrr_lakeoffire = world.get_entrance("Start Level - LRR - Lake Of Fire")
    entrance_lrr_lavalaughter = world.get_entrance("Start Level - LRR - Lava Laughter")
    entrance_lrr_oresome = world.get_entrance("Start Level - LRR - Oresome")
    entrance_lrr_rockhard = world.get_entrance("Start Level - LRR - Rock Hard")
    entrance_lrr_rockyhorror = world.get_entrance("Start Level - LRR - Rocky Horror")
    entrance_lrr_rubbletrouble = world.get_entrance("Start Level - LRR - Rubble Trouble")
    entrance_lrr_runthegauntlet = world.get_entrance("Start Level - LRR - Run The Gauntlet")
    entrance_lrr_searchandrescue = world.get_entrance("Start Level - LRR - Search And Rescue")
    entrance_lrr_splitdownthemiddle = world.get_entrance("Start Level - LRR - Split Down The Middle")
    entrance_lrr_thepathtopower = world.get_entrance("Start Level - LRR - The Path To Power")
    entrance_lrr_waterlotoffun = world.get_entrance("Start Level - LRR - Water Lot Of Fun")
    entrance_lrr_waterworks = world.get_entrance("Start Level - LRR - Water Works")

    world.set_rule(entrance_lrr_abreathoffreshair, (rule_can_breathe & Has("Level Access: LRR - A Breath Of Fresh Air")))
    world.set_rule(entrance_lrr_airraiders, Has("Level Access: LRR - Air Raiders"))
    world.set_rule(entrance_lrr_backtobasics, (rule_can_blast & rule_can_breathe & Has("Level Access: LRR - Back To Basics")))
    world.set_rule(entrance_lrr_breathless, (rule_can_blast & Has("Level Access: LRR - Breathless") & rule_can_always_breathe))
    world.set_rule(entrance_lrr_dontpanic, Has("Level Access: LRR - Don't Panic"))
    world.set_rule(entrance_lrr_drillernight, Has("Level Access: LRR - Driller Night"))
    world.set_rule(entrance_lrr_erodeworks, (rule_can_blast & Has("Level Access: LRR - Erode Works")))
    world.set_rule(entrance_lrr_explosiveaction, ((Has("Item Unlock: Dynamite") | rule_can_build_smalldigger | rule_can_build_mininglaser) & rule_can_build_supportstation & Has("Level Access: LRR - Explosive Action")))
    world.set_rule(entrance_lrr_fireandwater, (rule_can_breathe & rule_can_swim & Has("Level Access: LRR - Fire And Water")))
    world.set_rule(entrance_lrr_frozenfrenzy, (rule_can_blast & Has("Level Access: LRR - Frozen Frenzy") & rule_can_always_breathe))
    world.set_rule(entrance_lrr_hotstuff, (rule_can_breathe & Has("Level Access: LRR - Hot Stuff")))
    world.set_rule(entrance_lrr_icespy, (rule_can_breathe & Has("Level Access: LRR - Ice Spy")))
    world.set_rule(entrance_lrr_itsaholdup, Has("Level Access: LRR - It's A Hold Up"))
    world.set_rule(entrance_lrr_lakeoffire, Has("Level Access: LRR - Lake Of Fire"))
    world.set_rule(entrance_lrr_lavalaughter, (rule_can_breathe & Has("Level Access: LRR - Lava Laughter")))
    world.set_rule(entrance_lrr_oresome, Has("Level Access: LRR - Oresome"))
    world.set_rule(entrance_lrr_rockhard, ((Has("Item Unlock: Dynamite") | rule_can_build_mininglaser) & Has("Level Access: LRR - Rock Hard") & rule_can_always_breathe))
    world.set_rule(entrance_lrr_rockyhorror, (rule_can_breathe & Has("Level Access: LRR - Rocky Horror")))
    world.set_rule(entrance_lrr_rubbletrouble, Has("Level Access: LRR - Rubble Trouble"))
    world.set_rule(entrance_lrr_runthegauntlet, Has("Level Access: LRR - Run The Gauntlet"))
    world.set_rule(entrance_lrr_searchandrescue, (rule_can_swim & Has("Level Access: LRR - Search And Rescue")))
    world.set_rule(entrance_lrr_splitdownthemiddle, Has("Level Access: LRR - Split Down The Middle"))
    world.set_rule(entrance_lrr_thepathtopower, (rule_can_build_powerstation & Has("Level Access: LRR - The Path To Power")))
    world.set_rule(entrance_lrr_waterlotoffun, ((rule_can_build_rapidrider | rule_can_build_cargocarrier | rule_can_build_tunnelscout) & (rule_can_build_toolstore | ((Has("Item Unlock: Dynamite") | rule_can_build_mininglaser) & rule_can_breathe) | (rule_can_build_rapidrider & rule_can_blast & rule_can_breathe)) & Has("Level Access: LRR - Water Lot Of Fun") & rule_can_always_breathe))
    world.set_rule(entrance_lrr_waterworks, (rule_can_swim & Has("Level Access: LRR - Water Works") & rule_can_always_breathe))
    
    #LRRR

    entrance_lrrr_abreathoffreshair = world.get_entrance("Start Level - LRRR - A Breath Of Fresh Air")
    entrance_lrrr_airraiders = world.get_entrance("Start Level - LRRR - Air Raiders")
    entrance_lrrr_backtobasics = world.get_entrance("Start Level - LRRR - Back To Basics")
    entrance_lrrr_breathless = world.get_entrance("Start Level - LRRR - Breathless")
    entrance_lrrr_dontpanic = world.get_entrance("Start Level - LRRR - Don't Panic")
    entrance_lrrr_drillernight = world.get_entrance("Start Level - LRRR - Driller Night")
    entrance_lrrr_erodeworks = world.get_entrance("Start Level - LRRR - Erode Works")
    entrance_lrrr_explosiveaction = world.get_entrance("Start Level - LRRR - Explosive Action")
    entrance_lrrr_fireandwater = world.get_entrance("Start Level - LRRR - Fire And Water")
    entrance_lrrr_frozenfrenzy = world.get_entrance("Start Level - LRRR - Frozen Frenzy")
    entrance_lrrr_hotstuff = world.get_entrance("Start Level - LRRR - Hot Stuff")
    entrance_lrrr_icespy = world.get_entrance("Start Level - LRRR - Ice Spy")
    entrance_lrrr_itsaholdup = world.get_entrance("Start Level - LRRR - It's A Hold Up")
    entrance_lrrr_lakeoffire = world.get_entrance("Start Level - LRRR - Lake Of Fire")
    entrance_lrrr_lavalaughter = world.get_entrance("Start Level - LRRR - Lava Laughter")
    entrance_lrrr_oresome = world.get_entrance("Start Level - LRRR - Oresome")
    entrance_lrrr_rockhard = world.get_entrance("Start Level - LRRR - Rock Hard")
    entrance_lrrr_rockyhorror = world.get_entrance("Start Level - LRRR - Rocky Horror")
    entrance_lrrr_rubbletrouble = world.get_entrance("Start Level - LRRR - Rubble Trouble")
    entrance_lrrr_runthegauntlet = world.get_entrance("Start Level - LRRR - Run The Gauntlet")
    entrance_lrrr_searchandrescue = world.get_entrance("Start Level - LRRR - Search And Rescue")
    entrance_lrrr_splitdownthemiddle = world.get_entrance("Start Level - LRRR - Split Down The Middle")
    entrance_lrrr_thepathtopower = world.get_entrance("Start Level - LRRR - The Path To Power")
    entrance_lrrr_waterlotoffun = world.get_entrance("Start Level - LRRR - Water Lot Of Fun")
    entrance_lrrr_waterworks = world.get_entrance("Start Level - LRRR - Water Works")   

    world.set_rule(entrance_lrrr_abreathoffreshair, (rule_can_breathe & Has("Item Unlock: Dynamite") & Has("Level Access: LRRR - A Breath Of Fresh Air")))
    world.set_rule(entrance_lrrr_airraiders, (rule_can_breathe & rule_can_blast & Has("Level Access: LRRR - Air Raiders")))
    world.set_rule(entrance_lrrr_backtobasics, (rule_can_breathe & rule_can_build_toolstore & rule_can_build_upgradestation & Has("Item Unlock: Electric Fence") & Has("Level Access: LRRR - Back To Basics")))
    world.set_rule(entrance_lrrr_breathless, (rule_can_breathe & rule_can_build_geologicalcenter & Has("Level Access: LRRR - Breathless")))
    world.set_rule(entrance_lrrr_dontpanic, Has("Level Access: LRRR - Don't Panic"))
    world.set_rule(entrance_lrrr_drillernight, Has("Level Access: LRRR - Driller Night"))
    world.set_rule(entrance_lrrr_erodeworks, (Has("Item Unlock: Dynamite") & Has("Level Access: LRRR - Erode Works")))
    world.set_rule(entrance_lrrr_explosiveaction, (rule_can_swim & rule_can_build_supportstation & Has("Level Access: LRRR - Explosive Action")))
    world.set_rule(entrance_lrrr_fireandwater, (rule_can_breathe & (rule_can_build_rapidrider | rule_can_fly) & Has("Level Access: LRRR - Fire And Water")))
    world.set_rule(entrance_lrrr_frozenfrenzy, (rule_can_breathe & rule_can_blast & (rule_can_flydrill | rule_can_build_rapidrider) & Has("Level Access: LRRR - Frozen Frenzy")))
    world.set_rule(entrance_lrrr_hotstuff, (rule_can_breathe & rule_can_build_toolstore & rule_can_fly & Has("Level Access: LRRR - Hot Stuff")))
    world.set_rule(entrance_lrrr_icespy, (rule_can_breathe & Has("Level Access: LRRR - Ice Spy")))
    world.set_rule(entrance_lrrr_itsaholdup, (rule_can_build_orerefinery & (rule_can_lase | rule_can_swim | rule_can_jump | Has("Item Unlock: Dynamite")) & Has("Level Access: LRRR - It's A Hold Up")))
    world.set_rule(entrance_lrrr_lakeoffire, (rule_can_breathe & rule_can_flying_lase & Has("Level Access: LRRR - Lake Of Fire")))
    world.set_rule(entrance_lrrr_lavalaughter, (rule_can_breathe & Has("Level Access: LRRR - Lava Laughter")))
    world.set_rule(entrance_lrrr_oresome, (rule_can_breathe & Has("Level Access: LRRR - Oresome")))
    world.set_rule(entrance_lrrr_rockhard, ((rule_can_build_smalldigger | rule_can_build_mininglaser | Has("Item Unlock: Dynamite")) & rule_can_breathe & Has("Level Access: LRRR - Rock Hard")))
    world.set_rule(entrance_lrrr_rockyhorror, (rule_can_breathe & rule_can_build_toolstore & rule_can_build_canteen & Has("Vehicle Unlock: Small Transport Truck") & Has("Level Access: LRRR - Rocky Horror")))
    world.set_rule(entrance_lrrr_rubbletrouble, (Has("Building Unlock: Tool Store") & Has("Level Access: LRRR - Rubble Trouble")))
    world.set_rule(entrance_lrrr_runthegauntlet, Has("Level Access: LRRR - Run The Gauntlet"))
    world.set_rule(entrance_lrrr_searchandrescue, (rule_can_build_rapidrider | (rule_can_build_tunnelscout & rule_can_build_upgradestation) | (rule_can_build_smlc & rule_can_build_cargocarrier)) & Has("Level Access: LRRR - Search And Rescue"))
    world.set_rule(entrance_lrrr_splitdownthemiddle, (Has("Item Unlock: Dynamite") & Has("Level Access: LRRR - Split Down The Middle")))
    world.set_rule(entrance_lrrr_thepathtopower, (rule_can_build_powerstation & Has("Item Unlock: Electric Fence") & Has("Level Access: LRRR - The Path To Power")))
    world.set_rule(entrance_lrrr_waterlotoffun, (rule_can_build_docks & (rule_can_build_rapidrider | rule_can_build_tunnelscout) & Has("Item Unlock: Dynamite") & Has("Building Unlock: Tool Store") & Has("Level Access: LRRR - Water Lot Of Fun") & rule_can_always_breathe))
    world.set_rule(entrance_lrrr_waterworks, (rule_can_build_docks & (rule_can_build_toolstore | rule_can_build_tunneltransport) & (rule_can_build_tunnelscout | rule_can_build_rapidrider) & Has("Level Access: LRRR - Water Works")))
    
    #LRRC

    entrance_lrrc_abreathoffreshair = world.get_entrance("Start Level - LRRC - A Breath Of Fresh Air")
    entrance_lrrc_airraiders = world.get_entrance("Start Level - LRRC - Air Raiders")
    entrance_lrrc_backtobasics = world.get_entrance("Start Level - LRRC - Back To Basics")
    entrance_lrrc_breathless = world.get_entrance("Start Level - LRRC - Breathless")
    entrance_lrrc_dontpanic = world.get_entrance("Start Level - LRRC - Don't Panic")
    entrance_lrrc_drillernight = world.get_entrance("Start Level - LRRC - Driller Night")
    entrance_lrrc_erodeworks = world.get_entrance("Start Level - LRRC - Erode Works")
    entrance_lrrc_explosiveaction = world.get_entrance("Start Level - LRRC - Explosive Action")
    entrance_lrrc_fireandwater = world.get_entrance("Start Level - LRRC - Fire And Water")
    entrance_lrrc_frozenfrenzy = world.get_entrance("Start Level - LRRC - Frozen Frenzy")
    entrance_lrrc_hotstuff = world.get_entrance("Start Level - LRRC - Hot Stuff")
    entrance_lrrc_icespy = world.get_entrance("Start Level - LRRC - Ice Spy")
    entrance_lrrc_itsaholdup = world.get_entrance("Start Level - LRRC - It's A Hold Up")
    entrance_lrrc_lakeoffire = world.get_entrance("Start Level - LRRC - Lake Of Fire")
    entrance_lrrc_lavalaughter = world.get_entrance("Start Level - LRRC - Lava Laughter")
    entrance_lrrc_oresome = world.get_entrance("Start Level - LRRC - Oresome")
    entrance_lrrc_rockhard = world.get_entrance("Start Level - LRRC - Rock Hard")
    entrance_lrrc_rockyhorror = world.get_entrance("Start Level - LRRC - Rocky Horror")
    entrance_lrrc_rubbletrouble = world.get_entrance("Start Level - LRRC - Rubble Trouble")
    entrance_lrrc_runthegauntlet = world.get_entrance("Start Level - LRRC - Run The Gauntlet")
    entrance_lrrc_searchandrescue = world.get_entrance("Start Level - LRRC - Search And Rescue")
    entrance_lrrc_splitdownthemiddle = world.get_entrance("Start Level - LRRC - Split Down The Middle")
    entrance_lrrc_thepathtopower = world.get_entrance("Start Level - LRRC - The Path To Power")
    entrance_lrrc_waterlotoffun = world.get_entrance("Start Level - LRRC - Water Lot Of Fun")
    entrance_lrrc_waterworks = world.get_entrance("Start Level - LRRC - Water Works")

    world.set_rule(entrance_lrrc_abreathoffreshair, (rule_can_breathe & Has("Level Access: LRRC - A Breath Of Fresh Air")))
    world.set_rule(entrance_lrrc_airraiders, Has("Level Access: LRRC - Air Raiders"))
    world.set_rule(entrance_lrrc_backtobasics, (rule_can_breathe & Has("Level Access: LRRC - Back To Basics")))
    world.set_rule(entrance_lrrc_breathless, ((Has("Item Unlock: Dynamite") | rule_can_build_smalldigger | rule_can_build_granitegrinder | rule_can_build_mininglaser | rule_can_build_smlc) & Has("Level Access: LRRC - Breathless") & rule_can_always_breathe))
    world.set_rule(entrance_lrrc_dontpanic, Has("Level Access: LRRC - Don't Panic"))
    world.set_rule(entrance_lrrc_drillernight, Has("Level Access: LRRC - Driller Night"))
    world.set_rule(entrance_lrrc_erodeworks, (rule_can_blast & Has("Level Access: LRRC - Erode Works")))
    world.set_rule(entrance_lrrc_explosiveaction, ((rule_can_build_smalldigger | rule_can_build_mininglaser | Has("Item Unlock: Dynamite")) & rule_can_build_supportstation & Has("Level Access: LRRC - Explosive Action")))
    world.set_rule(entrance_lrrc_fireandwater, (rule_can_breathe & rule_can_swim & (rule_can_build_toolstore | rule_can_build_tunneltransport) & Has("Level Access: LRRC - Fire And Water")))
    world.set_rule(entrance_lrrc_frozenfrenzy, (rule_can_blast & Has("Level Access: LRRC - Frozen Frenzy") & rule_can_always_breathe))
    world.set_rule(entrance_lrrc_hotstuff, (rule_can_breathe & Has("Level Access: LRRC - Hot Stuff")))
    world.set_rule(entrance_lrrc_icespy, (Has("Level Access: LRRC - Ice Spy") & rule_can_always_breathe))
    world.set_rule(entrance_lrrc_itsaholdup, Has("Level Access: LRRC - It's A Hold Up"))
    world.set_rule(entrance_lrrc_lakeoffire, Has("Level Access: LRRC - Lake Of Fire"))
    world.set_rule(entrance_lrrc_lavalaughter, (Has("Level Access: LRRC - Lava Laughter") & rule_can_always_breathe))
    world.set_rule(entrance_lrrc_oresome, Has("Level Access: LRRC - Oresome"))
    world.set_rule(entrance_lrrc_rockhard, (rule_can_blast & Has("Level Access: LRRC - Rock Hard") & rule_can_always_breathe))
    world.set_rule(entrance_lrrc_rockyhorror, (rule_can_breathe & Has("Level Access: LRRC - Rocky Horror")))
    world.set_rule(entrance_lrrc_rubbletrouble, Has("Level Access: LRRC - Rubble Trouble"))
    world.set_rule(entrance_lrrc_runthegauntlet, Has("Level Access: LRRC - Run The Gauntlet"))
    world.set_rule(entrance_lrrc_searchandrescue, (rule_can_swim & Has("Level Access: LRRC - Search And Rescue")))
    world.set_rule(entrance_lrrc_splitdownthemiddle, Has("Level Access: LRRC - Split Down The Middle"))
    world.set_rule(entrance_lrrc_thepathtopower, (rule_can_build_powerstation & Has("Level Access: LRRC - The Path To Power")))
    world.set_rule(entrance_lrrc_waterlotoffun, ((rule_can_swim | rule_can_blast) & Has("Level Access: LRRC - Water Lot Of Fun") & rule_can_always_breathe))
    world.set_rule(entrance_lrrc_waterworks, (Has("Level Access: LRRC - Water Works") & rule_can_always_breathe))
    
    #BAZ
    
    # entrance_baz_abreathoffreshair = world.get_entrance("Start Level - BAZ - A Breath Of Fresh Air")
    # entrance_baz_airraiders = world.get_entrance("Start Level - BAZ - Air Raiders")
    # entrance_baz_backtobasics = world.get_entrance("Start Level - BAZ - Back To Basics")
    # entrance_baz_breathless = world.get_entrance("Start Level - BAZ - Breathless")
    # entrance_baz_coldcomfort = world.get_entrance("Start Level - BAZ - Cold Comfort")
    # entrance_baz_dontpanic = world.get_entrance("Start Level - BAZ - Don't Panic")
    # entrance_baz_downinthedirt = world.get_entrance("Start Level - BAZ - Down In The Dirt")
    # entrance_baz_drillernight = world.get_entrance("Start Level - BAZ - Driller Night")
    # entrance_baz_erodeworks = world.get_entrance("Start Level - BAZ - Erode Works")
    # entrance_baz_explosiveaction = world.get_entrance("Start Level - BAZ - Explosive Action")
    # entrance_baz_fireandwater = world.get_entrance("Start Level - BAZ - Fire And Water")
    # entrance_baz_frozenfrenzy = world.get_entrance("Start Level - BAZ - Frozen Frenzy")
    # entrance_baz_hotstuff = world.get_entrance("Start Level - BAZ - Hot Stuff")
    # entrance_baz_icespy = world.get_entrance("Start Level - BAZ - Ice Spy")
    # entrance_baz_itsaholdup = world.get_entrance("Start Level - BAZ - It's A Hold Up")
    # entrance_baz_lakeoffire = world.get_entrance("Start Level - BAZ - Lake Of Fire")
    # entrance_baz_lavalaughter = world.get_entrance("Start Level - BAZ - Lava Laughter")
    # entrance_baz_mineovermatter = world.get_entrance("Start Level - BAZ - Mine Over Matter")
    # entrance_baz_moltenmeltdown = world.get_entrance("Start Level - BAZ - Molten Meltdown")
    # entrance_baz_recruitment = world.get_entrance("Start Level - BAZ - Recruitment")
    # entrance_baz_oresome = world.get_entrance("Start Level - BAZ - Oresome")
    # entrance_baz_rockhard = world.get_entrance("Start Level - BAZ - Rock Hard")
    # entrance_baz_rockyhorror = world.get_entrance("Start Level - BAZ - Rocky Horror")
    # entrance_baz_rubbletrouble = world.get_entrance("Start Level - BAZ - Rubble Trouble")
    # entrance_baz_runthegauntlet = world.get_entrance("Start Level - BAZ - Run The Gauntlet")
    # entrance_baz_seamless = world.get_entrance("Start Level - BAZ - Seamless")
    # entrance_baz_searchandrescue = world.get_entrance("Start Level - BAZ - Search And Rescue")
    # entrance_baz_slimeysimple = world.get_entrance("Start Level - BAZ - Slimey Simple")
    # entrance_baz_splitdownthemiddle = world.get_entrance("Start Level - BAZ - Split Down The Middle")
    # entrance_baz_thehardrocklife = world.get_entrance("Start Level - BAZ - The Hard Rock Life")
    # entrance_baz_thepathtopower = world.get_entrance("Start Level - BAZ - The Path To Power")
    # entrance_baz_waterlotoffun = world.get_entrance("Start Level - BAZ - Water Lot Of Fun")
    # entrance_baz_waterworks = world.get_entrance("Start Level - BAZ - Water Works")
    
    # world.set_rule(entrance_baz_abreathoffreshair, Has("Level Access: BAZ - A Breath Of Fresh Air"))
    # world.set_rule(entrance_baz_airraiders, Has("Level Access: BAZ - Air Raiders"))
    # world.set_rule(entrance_baz_backtobasics, Has("Level Access: BAZ - Back To Basics"))
    # world.set_rule(entrance_baz_breathless, Has("Level Access: BAZ - Breathless"))
    # world.set_rule(entrance_baz_coldcomfort, Has("Level Access: BAZ - Cold Comfort"))
    # world.set_rule(entrance_baz_dontpanic, Has("Level Access: BAZ - Don't Panic"))
    # world.set_rule(entrance_baz_downinthedirt, Has("Level Access: BAZ - Down In The Dirt"))
    # world.set_rule(entrance_baz_drillernight, Has("Level Access: BAZ - Driller Night"))
    # world.set_rule(entrance_baz_erodeworks, Has("Level Access: BAZ - Erode Works"))
    # world.set_rule(entrance_baz_explosiveaction, Has("Level Access: BAZ - Explosive Action"))
    # world.set_rule(entrance_baz_fireandwater, Has("Level Access: BAZ - Fire And Water"))
    # world.set_rule(entrance_baz_frozenfrenzy, Has("Level Access: BAZ - Frozen Frenzy"))
    # world.set_rule(entrance_baz_hotstuff, Has("Level Access: BAZ - Hot Stuff"))
    # world.set_rule(entrance_baz_icespy, Has("Level Access: BAZ - Ice Spy"))
    # world.set_rule(entrance_baz_itsaholdup, Has("Level Access: BAZ - It's A Hold Up"))
    # world.set_rule(entrance_baz_lakeoffire, Has("Level Access: BAZ - Lake Of Fire"))
    # world.set_rule(entrance_baz_lavalaughter, Has("Level Access: BAZ - Lava Laughter"))
    # world.set_rule(entrance_baz_mineovermatter, Has("Level Access: BAZ - Mine Over Matter"))
    # world.set_rule(entrance_baz_moltenmeltdown, Has("Level Access: BAZ - Molten Meltdown"))
    # world.set_rule(entrance_baz_recruitment, Has("Level Access: BAZ - Recruitment"))
    # world.set_rule(entrance_baz_oresome, Has("Level Access: BAZ - Oresome"))
    # world.set_rule(entrance_baz_rockhard, Has("Level Access: BAZ - Rock Hard"))
    # world.set_rule(entrance_baz_rockyhorror, Has("Level Access: BAZ - Rocky Horror"))
    # world.set_rule(entrance_baz_rubbletrouble, Has("Level Access: BAZ - Rubble Trouble"))
    # world.set_rule(entrance_baz_runthegauntlet, Has("Level Access: BAZ - Run The Gauntlet"))
    # world.set_rule(entrance_baz_seamless, Has("Level Access: BAZ - Seamless"))
    # world.set_rule(entrance_baz_searchandrescue, Has("Level Access: BAZ - Search And Rescue"))
    # world.set_rule(entrance_baz_slimeysimple, Has("Level Access: BAZ - Slimey Simple"))
    # world.set_rule(entrance_baz_splitdownthemiddle, Has("Level Access: BAZ - Split Down The Middle"))
    # world.set_rule(entrance_baz_thehardrocklife, Has("Level Access: BAZ - The Hard Rock Life"))
    # world.set_rule(entrance_baz_thepathtopower, Has("Level Access: BAZ - The Path To Power"))
    # world.set_rule(entrance_baz_waterlotoffun, Has("Level Access: BAZ - Water Lot Of Fun"))
    # world.set_rule(entrance_baz_waterworks, Has("Level Access: BAZ - Water Works"))

def set_all_location_rules(world: ManicMinersWorld) -> None:
    goal_achievable = world.get_location("Goal Conditions Achievable")
    if world.options.victory_condition in [0,1,2]:
        set_rule(goal_achievable, lambda state: state.has("Level Completed", world.player, world.options.target_level_count))
    
def set_completion_condition(world: ManicMinersWorld) -> None:
    world.multiworld.completion_condition[world.player] = lambda state: state.has("Victory", world.player)
